# Generated by Django 5.1.1 on 2024-09-27 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65)),
                ('decricao', models.CharField(max_length=165)),
                ('slug', models.SlugField()),
                ('tempo_preparacao', models.IntegerField()),
                ('tempo_preparacao_unidade', models.CharField(max_length=12)),
                ('porcoes', models.IntegerField()),
                ('porcoes_unidade', models.CharField(max_length=12)),
                ('modo_preparacao', models.TextField()),
                ('modo_preparacao_is_html', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('is_publicado', models.BooleanField(default=False)),
                ('capa', models.ImageField(upload_to='receita/capa/%Y/%m/%d/')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria')),
            ],
        ),
    ]
